application/models.py
# models.py

from flask_login import UserMixin
from . import db

class Users(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(100), unique=True)
    username = db.Column(db.String(50), unique=True)
    password = db.Column(db.String(250))
    firstName = db.Column(db.String(50))
    lastName = db.Column(db.String(50))
    chaseTheAceWins = db.Column(db.Integer)

class Player(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    userId = db.Column(db.Integer)
    roomId = db.Column(db.Integer)
    generatedPlayerId = db.Column(db.String(100), unique=True)
    name = db.Column(db.String(100))
    card = db.Column(db.String(20))
    lives = db.Column(db.Integer)
    outOfGame = db.Column(db.Boolean)
    socketId = db.Column(db.String(50))
#     Need to be careful because shed players could have the same room id. Need gameType parameter.

class Room(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    roomId = db.Column(db.Integer, unique=True)
    password = db.Column(db.String(40))
    gameType = db.Column(db.String(20))
    numberOfLivesSet = db.Column(db.Integer)
    hostPlayerId = db.Column(db.String(100))
    currentPlayerId = db.Column(db.String(100))
    dealerPlayerId = db.Column(db.String(100))
    winningPlayerId = db.Column(db.String(100))
    locked = db.Column(db.Boolean)
    deck = db.Column(db.String(1000))

application/__init__.py
#!/usr/bin/python3

import os
from flask import Flask, session
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
import configparser
from flask_session import Session
from flask_socketio import SocketIO, emit, send, join_room, leave_room

config = configparser.ConfigParser()
config.read("settings.conf")

# init SQLAlchemy so we can use it later
db = SQLAlchemy()
socketio = SocketIO()
login_manager = LoginManager()
from . import models

def create_app():

    app = Flask(__name__)
    if os.environ['FLASK_ENV'] == 'production':
        app.config['SECRET_KEY'] = os.environ['SECRET_KEY']
        app.config['SQLALCHEMY_DATABASE_URI'] = os.environ['DATABASE_URL']
    else:
        app.config['SECRET_KEY'] = config.get('SQLALCHEMY', 'secret_key')
        app.config['SQLALCHEMY_DATABASE_URI'] = config.get('SQLALCHEMY', 'sqlalchemy_database_uri')
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
    app.config['SESSION_TYPE'] = 'filesystem'
    app.url_map.strict_slashes = False

    db.init_app(app)
    Session(app)
    if os.environ['FLASK_ENV'] == 'production':
        socketio.init_app(app, manage_session=False, async_mode='eventlet', async_handlers=True)
    else:
        socketio.init_app(app, manage_session=False)
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    registerBlueprints(app)

    return app


def registerBlueprints(app):
    # blueprint for auth routes in our app
    from .controllers.auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint)

    # blueprint for non-auth parts of app
    from .controllers.main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    # blueprint for chase_the_ace parts of app, Game sockets import game mechanics and socketio listeners.
    from .controllers.games.chaseTheAce import chase_the_ace as chase_the_ace_blueprint
    from .controllers.games import chaseTheAceGameplay
    from .controllers.games import chaseTheAceRedirects
    from .controllers import chat
    app.register_blueprint(chase_the_ace_blueprint)

    # blueprint for shed parts of app
    from .controllers.games.shed import shed as shed_blueprint
    app.register_blueprint(shed_blueprint)


@login_manager.user_loader
def load_user(user_id):
    return models.Users.query.get(int(user_id))

@socketio.on('connect')
def handle_my_connect_event():
    print('connected')

@socketio.on('disconnect')
def handle_my_disconnect_event():
    print('disconnected')

application/controllers/auth.py
# auth.py

from flask import Blueprint, render_template, redirect, url_for, request, flash, session
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, logout_user, login_required, current_user
from .. import models
from .. import db

auth = Blueprint('auth', __name__)

@auth.route('/login')
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.profile'))
    else:
        return render_template('home/login.html')

@auth.route('/signup')
def signup():
    if current_user.is_authenticated:
        return redirect(url_for('main.profile'))
    else:
        return render_template('home/signup.html')

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.index'))

@auth.route('/signup', methods=['POST'])
def signup_post():
    email = request.form.get('email')
    username = request.form.get('username')
    password = request.form.get('password')
    firstName = request.form.get('firstName')
    lastName = request.form.get('lastName')

    user = models.Users.query.filter_by(email = email).first()

    if user:
        flash('Email address already exists')
        return redirect(url_for('auth.signup'))

    newUser = models.Users(email = email, username = username, password = generate_password_hash(password, method='sha256'), firstName = firstName, lastName = lastName, chaseTheAceWins = 0)

    db.session.add(newUser)
    db.session.commit()

    return redirect(url_for('auth.login'))

@auth.route('/login', methods=['POST'])
def login_post():

    email = request.form.get('email')
    password = request.form.get('password')
    username = request.form.get('username')
    remember = True if request.form.get('remember') else False
    # Investigate above remember to see if it works. Also look at remembering credentials, not keeping thme signed in. Put two separate checkboxes?

    user = models.Users.query.filter_by(email = email).first()

    if user:
        if check_password_hash(user.password, password):
            login_user(user, remember = remember)
            session['userFullName'] = current_user.firstName + ' ' + current_user.lastName
            session['userId'] = current_user.id
            return redirect(url_for('main.profile'))
        else:
            flash('Incorrect password')
            return redirect(url_for('auth.login'))
    else:
        flash('Account with this email does not exist')
        return redirect(url_for('auth.login'))
    # refactor to include username or password. Logic should be easy.

application/controllers/chat.py
from flask import session
from .. import socketio, send, emit

@socketio.on("send chat message")
def manageMessage(chatMessage):
    roomId = session.get("roomId")
    playerName = session.get("userFullName")
    emit("append on chat", (playerName, chatMessage), room=roomId)

application/controllers/game_chat.py
from flask import session
from .. import socketio, send, emit

@socketio.on("send chat message")
def manageMessage(chatMessage):
    roomId = session.get("roomId")
    playerName = session.get("userFullName")
    emit("append on chat", (playerName, chatMessage), room=roomId)

application/controllers/main.py
# main.py

from flask import Blueprint, render_template, session
from flask_login import login_required, current_user
from .. import db
from .. import models

main = Blueprint('main', __name__)

@main.route('/')
def index():
    return render_template('home/index.html')

@main.route('/profile')
@login_required
def profile():
    userId = session.get('userId')
    chaseTheAceWins = models.Users.query.filter_by(id=userId).first().chaseTheAceWins
    return render_template('home/profile.html', name=current_user.firstName, chaseTheAceWins=chaseTheAceWins)

@main.route('/play')
def play():
    return render_template('home/play.html')

application/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" type= "text/css" href="{{ url_for('static', filename='css/basePage.css') }}">
    {% block head %}
    {% endblock %}
  </head>
  <body>
    <nav class="navBar">
      <div class="logo">
        Card Games Online
      </div>
      <div class="">
        <div class="links">
          <a href="{{url_for('main.index')}}">Home</a>
          {% if current_user.is_authenticated %}
          <a href="{{url_for('main.profile')}}">Profile</a>
          {% endif %}
          <a href="{{url_for('main.play')}}">Play</a>
          {% if not current_user.is_authenticated %}
          <a href="{{url_for('auth.login')}}">Login</a>
          <a href="{{url_for('auth.signup')}}">Sign Up</a>
          {% endif %}
          {% if current_user.is_authenticated %}
          <a href="{{url_for('auth.logout')}}">Logout</a>
          {% endif %}
        </div>
      </div>
    </nav>
    <div class="main">
        {% block content %}
        {% endblock %}
    </div>
  </body>
</html>

application/templates/games/chase_the_ace/game.html
{% extends "base.html" %}

{% block head %}
    {% include "games/gamesHead.html" %}
{% endblock %}

{% block content %}
    <div class="backButton">
        <a href="{{url_for('chase_the_ace.chase_the_ace_index')}}">Back</a>
    </div>
    <div class="mainContainer">
        <div class="gameHeader">
            <h1>Chase The Ace</h1>
        </div>
        <div id="canvasWrapper">
        <div id="gameCanvas" class="gameCanvas"></div>
            {% block chat %}
            {% include "utils/chat.html" %}
            {% endblock %}
        </div>
    </div>

<script type='text/javascript' src="{{ url_for('static', filename='js/chase_the_ace/game/GamePage.js') }}"></script>
<script type='text/javascript' src="{{ url_for('static', filename='js/chase_the_ace/game/game.js') }}"></script>


{% endblock %}

application/templates/games/chase_the_ace/head/indexHead.html
<script src="//cdnjs.cloudflare.com/ajax/libs/socket.io/2.2.0/socket.io.js" integrity="sha256-yr4fRk/GU1ehYJPAs8P4JlTgu0Hdsp4ZKrx8bDEDC3I=" crossorigin="anonymous"></script>
<script src="{{ url_for('static', filename='js/phaser.js') }}"></script>
<script>
    // Initialisation of socket variable into the global scope.
    self.socket = io();
    socket.on('redirect', function (data)
    {
        window.location = data.url;
    });
</script>

application/templates/games/chase_the_ace/index.html
{% extends "base.html" %}

{% block head %}
    {% include "games/gamesHead.html" %}
{% endblock %}

{% block content %}
<div class="backButton">
  <a href="{{url_for('main.play')}}">Back</a>
</div>
<div class="mainContainer">
    <div class="gameHeader">
        <h1>Chase The Ace</h1>
    </div>
    <div id="canvasWrapper">
        <div id="gameCanvas" class="gameCanvas"></div>
    </div>
</div>

<script type='text/javascript' src="{{ url_for('static', filename='js/chase_the_ace/StartPage.js') }}"></script>
<script type='text/javascript' src="{{ url_for('static', filename='js/chase_the_ace/HostPage.js') }}"></script>
<script type='text/javascript' src="{{ url_for('static', filename='js/chase_the_ace/JoinPage.js') }}"></script>
<script type='text/javascript' src="{{ url_for('static', filename='js/chase_the_ace/game.js') }}"></script>
{% endblock %}

application/templates/games/gamesHead.html
<script src="//cdnjs.cloudflare.com/ajax/libs/socket.io/2.2.0/socket.io.js" integrity="sha256-yr4fRk/GU1ehYJPAs8P4JlTgu0Hdsp4ZKrx8bDEDC3I=" crossorigin="anonymous"></script>
<script src="{{ url_for('static', filename='js/phaser.js') }}"></script>
<script>window.name = '{{ fullName }}'</script>
<script>
    // Initialisation of socket variable into the global scope.
    self.socket = io();
    socket.on('redirect', function (data)
    {
        window.location = data.url;
    });
</script>
<script>
    browserName = ''
     if((navigator.userAgent.indexOf("Opera") || navigator.userAgent.indexOf('OPR')) != -1 )
    {
        browserName = 'Opera';
    }
    else if(navigator.userAgent.indexOf("Chrome") != -1 )
    {
        browserName = 'Chrome';
    }
    else if(navigator.userAgent.indexOf("Safari") != -1)
    {
        browserName = 'Safari';
    }
    else if(navigator.userAgent.indexOf("Firefox") != -1 )
    {
        browserName = 'Firefox';
    }
    else if((navigator.userAgent.indexOf("MSIE") != -1 ) || (!!document.documentMode == true )) //IF IE > 10
    {
        browserName = 'IE';
    }
    else
    {
        browserName = 'unknown';
    }
    window.browser = browserName;
</script>
<link rel="stylesheet" type= "text/css" href="{{ url_for('static', filename='css/gamePage.css') }}">
<link rel="stylesheet" type= "text/css" href="{{ url_for('static', filename='css/gameInDevelopment.css') }}">

application/templates/games/shed/index.html
{% extends "base.html" %}

{% block head %}
{% include "games/gamesHead.html" %}
{% endblock %}

{% block content %}
<div class="backButton">
  <a href="{{url_for('main.play')}}">Back</a>
</div>
<!--<div class="gameHeader">-->
<!--    <h1>Shed</h1>-->
<!--</div>-->
<div class="gameInDevelopmentText">
    <h2>Still in development. Sorry for the inconvenience</h2>
</div>

{% endblock %}

application/templates/home/index.html
{% extends "base.html" %}

{% block content %}
<h1>Card Games Online</h1>
<h2>What we are</h2>
<p>This is a free, open source website which you can use to play a multitude of card games online with anyone with a browser. Just sign up, click on a game and start playing!</p>
{% endblock %}

application/templates/home/login.html
{% extends "base.html" %}
{% block content %}
<div class="">
  <h3>Login.... Please...</h3>
  <div class="">
    {% with messages = get_flashed_messages() %}
    {% if messages %}
    <div class="">
      {{ messages[0] }}. Go to <a href="{{url_for('auth.signup')}}">signup page</a>.
    </div>
    {% endif %}
    {% endwith %}
    <form action="/login" method="POST">
      <div class="">
        <div class="">
          <input id="login-email" type="email" name="email" placeholder="Your Email" autofocus="">
        </div>
      </div>
      <div class="">
        <div class="">
          <input id="login-password" type="password" name="password" placeholder="Your Password">
        </div>
      </div>
      <div class="">
        <label>
          <input id="keep-me-logged-in-checkbox" type="checkbox" name="keepMeSignedIn">
          Keep me logged in
        </label>
      </div>
      <button id="submit" name="button">Login</button>
    </form>
  </div>
</div>
{% endblock %}

application/templates/home/play.html
{% extends "base.html" %}

{% block content %}
<div class="">
  <h1>Play</h1>
  <h2>Select a game below</h2>
  <a href="{{url_for('chase_the_ace.chase_the_ace_index')}}">
    <img src="{{ url_for('static', filename='images/chase_the_ace.jpg') }}" alt="">
  </a>
  <a href="{{url_for('shed.shed_index')}}">
    <img src="{{ url_for('static', filename='images/chase_the_ace.jpg') }}" alt="">
  </a>
  </div>
{% endblock %}

application/templates/home/profile.html
{% extends "base.html" %}

{% block content %}
<h1>
    Welcome, {{ name }}!
</h1>
<h2>
    Chase the ace wins: {{ chaseTheAceWins }}
</h2>
{% endblock %}

application/templates/home/signup.html
{% extends "base.html" %}
{% block content %}
<div class="">
  <h3>Sign Up</h3>
  <div class="">
    {% with messages = get_flashed_messages() %}
    {% if messages %}
    <div class="">
      {{ messages[0] }}. Go to <a href="{{url_for('auth.login')}}">login page</a>.
    </div>
    {% endif %}
    {% endwith %}
    <form action="/signup" method="POST">
      <div class="">
        <div class="">
          <input id="sign-up-email" type="email" name="email" placeholder="Email" autofocus="">
        </div>
      </div>
      <div class="">
        <div class="">
          <input id="sign-up-username" type="text" name="username" placeholder="Username" autofocus="">
        </div>
      </div>
      <div class="">
        <div class="">
          <input id="sign-up-password" type="password" name="password" placeholder="Password">
        </div>
      </div>
      <div class="">
        <div class="">
          <input id="sign-up-first-name"type="text" name="firstName" placeholder="First name" autofocus="">
        </div>
      </div>
      <div class="">
        <div class="">
          <input id="sign-up-last-name" type="text" name="lastName" placeholder="Last name" autofocus="">
        </div>
      </div>
      <button id="submit" name="button">Sign Up</button>
    </form>
  </div>
</div>
{% endblock %}

application/templates/utils/chat.html
<link rel="stylesheet" type= "text/css" href="{{ url_for('static', filename='css/chat.css') }}">

<div class="chatContainer">
    <div class="chatHeader">
        <h3>Chat</h3>
    </div>
    <div class="chatCentre" id="chatCentre">
    </div>
    <div class="chatBottom">
        <form action="#" id="chatForm" onsubmit="sendMessage();return false">
            <input name="message" type="text" id="chatMessage"/>
            <button name="submit" type="submit" id="submitMessage">Send</button>
        </form>
    </div>
</div>

<script type='text/javascript' src="{{ url_for('static', filename='js/utils/chat.js') }}"></script>